name: clang-format check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format

      - name: Check formatting
        run: |
          find kernel drivers app samples \( -name '*.c' -o -name '*.h' \) | xargs clang-format --dry-run --Werror
